baseURL = 'https://christyjohn.github.io/'
languageCode = 'en-us'
title = 'christyjohn'
theme = 'PaperMod'
relativeURLs = false
canonifyURLs = true

[pagination]
pagerSize = 10

[params]
defaultTheme = "dark"
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
comments = true

[taxonomies]
category = "categories"
tag = "tags"

[[menu.main]]
identifier = "ask-ai-section"
name = "AI Conversations"
url = "/posts/ask-ai/"
weight = 1

[[menu.main]]
identifier = "java-section"
name = "Java"
url = "/posts/java/"
weight = 2

[[menu.main]]
identifier = "spring-section"
name = "Spring"
url = "/posts/spring/"
weight = 3

[[menu.main]]
identifier = "system-desgin-section"
name = "System Desgin"
url = "/posts/system-design/"
weight = 4


[[menu.main]]
identifier = "ds-algo-section"
name = "DS / Algorithms"
url = "/posts/ds-algo/"
weight = 5

[[menu.main]]
identifier = "misc-section"
name = "Misc"
url = "/posts/misc/"
weight = 99

[[menu.main]]
identifier = "about-page"
name = "About"
url = "/about/"
weight = 100